<?php
/**
 * @var \Overdose\Reviews\ViewModel\Reviews $viewModel
 * @var \Magento\Framework\View\Element\Template $block
 */

$viewModel = $block->getData('view_model');
?>





<h2 id="fh2">WE APPRECIATE YOUR REVIEW!</h2>
<h6 id="fh6">Your review will help us to improve our web hosting quality products, and customer services.</h6>

<form id="feedback" action="<?php echo $block->getUrl("reviews/reviews/reviewSave")?>" method="post">
    <div class="pinfo">Your personal info</div>

    <div class="form-group">
        <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input  name="username" placeholder="Your Name"  type="text">

            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                <input  name="title" placeholder="Review title" class="form-control"  type="text">
            </div>
        </div>
    </div>

    <div class="pinfo">Rate our overall services.</div>


    <div class="form-group">
        <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-heart"></i></span>
                <select class="form-control" name="rating" id="rate">
                    <option value="1star">1</option>
                    <option value="2stars">2</option>
                    <option value="3stars">3</option>
                    <option value="4stars">4</option>
                    <option value="5stars">5</option>
                </select>
            </div>
        </div>
    </div>

    <div class="pinfo">Write your feedback.</div>


    <div class="form-group">
        <div class="col-md-4 inputGroupContainer">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                <textarea name="description" class="form-control" id="review" rows="3"></textarea>

            </div>
        </div>
    </div>
    <input type="hidden" name="product_id" value="<?php echo $block->getRequest()->getParam('id') ?>">
    <input type="hidden" name="customer_id" value="<?php echo $viewModel->getCustomerId()?>">
    <button type="submit" class="btn btn-primary">Submit</button>


</form>
<?php echo $viewModel->getAvarageProductRating(); ?>

