<?php
/**
 * @var \Overdose\Reviews\ViewModel\Reviews $viewModel
 * @var \Magento\Framework\View\Element\Template $block
 */
$viewModel = $block->getData('view_model');
?>
<h2>test block</h2>
<?php foreach ($viewModel->getProductReviewById() as $item):?>
    <h1><?php echo $item->getUsername(); ?></h1>
<h1><?php echo $item->getTitle(); ?></h1>
<h1><?php echo $item->getDescription(); ?></h1>
<h1><?php echo $item->getRating(); ?></h1>
<?php endforeach; ?>


